name:                sandbox-reflex
version:             0.1.0.0
github:              "githubuser/sandbox-reflex"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sandbox-reflex#readme>

dependencies:
- base >=4.9 && <4.10
- reflex >= 0.5 && < 0.6
- reflex-dom >= 0.4 && < 0.5
- classy-prelude
- email-validate
- string-conv
- jsaddle-warp
- text
- file-embed
- containers
- bifunctors
- profunctors
library:
  source-dirs: src

executables:
  sandbox-reflex-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandbox-reflex

tests:
  sandbox-reflex-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandbox-reflex
